### PR TITLE
Added new tests

### PR DESCRIPTION
**Pull request by dashomeradio**
Added new tests to the Dreamcoil framework for testing the functionality.

### CODE REVIEW

**Comment by xolf** [comment]
Could you just add more tests for the constants.
Especially the new Constants like `DREAMCOIL_VERSION`.
Would be awesome :+1:

**Comment by dashomeradio** [comment]
If have just added `DREAMCOIL_VERSION`.

**Comment by xolf** [comment]
[LGTM](http://lgtm.in/i/AG2qaI7hq)

[:+1:](http://lgtm.in/u/AG2qaI7hq) [:-1:](http://lgtm.in/r/AG2qaI7hq)

**Comment by dashomeradio** [comment]
Fine

**Pull request merged**
